version: "3"
services:
  tgbot:
    restart: always
    image: hackroid/tg-dumb-bot:latest
    environment:
      - token=${token}
      - debug=${debug}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - pixiv
  pixiv:
    restart: always
    image: godmountain/pppixiv:latest
    environment:
      - username=${username}
      - password=${password}